services:
  django:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "${DJANGO_PORT}:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file: 
     - ../.env
    depends_on:
     - database
    volumes:
     - ../static:/app/static
     - ../media:/app/media
  redis:
    image: redis:latest
    container_name: redis
  celery:
    build:
      context: .. 
    command: celery --app=core.config.settings.celery worker -l INFO
    container_name: celery
    ports:
      - "8030:8000"
    env_file: 
     - ../.env
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  flower:
    image: mher/flower:latest
    container_name: flower
    command: celery --app=core.config.settings.celery flower
    build:
      context: .. 
    ports:
      - "5555:5555"
    env_file: 
     - ../.env
    depends_on:
      - redis
      - celery