name: Backend Docker

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Docker Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Make Application in Docker
      run: make app
    
    - name: Create Migrations
      run: make migrations
    
    - name: Run Migrate
      run: make migrate

    - name: Run Test
      run: make test

    - name: Show Pip List
      run: make piplist

    - name: Check Docker Container
      run: make check
